# syntax=docker/dockerfile:experimental
FROM rust:1.45 as builder
RUN cargo install sccache
WORKDIR /usr/src/zksync
COPY . .
RUN RUSTC_WRAPPER=/usr/local/cargo/bin/sccache \
    cargo build --release

FROM debian:buster-slim
RUN apt-get update && apt-get install -y libpq5 ca-certificates && rm -rf /var/lib/apt/lists/*
EXPOSE 3000
EXPOSE 3031
EXPOSE 3030
COPY --from=builder /usr/src/zksync/target/release/zksync_server /usr/bin
COPY contracts/build/ /contracts/build/
ENTRYPOINT ["zksync_server"]
